name: Deploy Docusaurus to Server

on:
  push:
    branches:
      - master # Запуск на коммитах в main

jobs:
  deploy:
    name: Build and Deploy to Server
    runs-on: ubuntu-latest

    steps:
      # Шаг 1. Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2. Установка Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Укажите вашу версию Node.js
#          cache: 'yarn'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-modules-

      # Шаг 3. Установка зависимостей
      - name: Install dependencies
        run: yarn install

      # Шаг 4. Сборка Docusaurus
      - name: Build Docusaurus
        run: yarn build

      - name: Serving Build
        run: |
          yarn serve > serve.log 2>&1 &
          echo $! > serve.pid

      - name: Install Puppeteer Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 \
            libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 \
            libgdk-pixbuf2.0-0 libglib2.0-0 libnspr4 libnss3 \
            libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-xcb1 \
            libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 \
            libxi6 libxrandr2 libxrender1 libxtst6 ca-certificates \
            fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

      # Шаг 3. Очистка кэша Puppeteer
      - name: Clear Puppeteer Cache
        run: rm -rf ~/.cache/puppeteer

      # Шаг 4. Установка Puppeteer и его браузера
      - name: Install Puppeteer Browser
        run: npx puppeteer install

      - name: Generate PDF
        run: yarn generate:pdf

      - name: Stop Serve Process
        run: kill $(cat serve.pid)

      # Шаг 8. Настройка SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server key to known_hosts
        run: echo "${{ secrets.SERVER_PUBLIC_KEY }}" >> ~/.ssh/known_hosts

      # Шаг 9. Копирование файлов на сервер
      - name: Deploy to Server
        run: |
          rsync -vrm --delete -e "ssh -o StrictHostKeyChecking=no" ./build/ ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/var/www/html/public/
